name = "SurfaceProfileReaders"
uuid = "6da23c8c-444c-4310-aaa6-9150b66cb193"
authors = ["Jaakko Ruohio <jaakkor2@gmail.com>"]
version = "0.1.4-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
Dates = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
